In [2]:
import sys
sys.path.append("/content/drive/Othercomputers/Mein PC/Completed")

In [3]:
%pip install ogb
%pip install funcy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 78 kB 3.9 MB/s 
  Created wheel for littleutils: filename=littleutils-0.2.2-py3-none-any.whl size=7047 sha256=753b8e382ecfcfbcce1d337f484daddb9865220d1c97b871a3b9088a0217e96a
  Stored in directory: /root/.cache/pip/wheels/6a/33/c4/0ef84d7f5568c2823e3d63a6e08988852fb9e4bc822034870a
Successfully built littleutils
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


# Neuer Abschnitt

In [33]:
%reload_ext autoreload
%autoreload 2
import numpy as np 
import tensorflow as tf 
from tensorflow import keras 
import batching 
import funcy as fy 
import math 

In [46]:
import modularized as m 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
first_entry = batching.dataset2[0]


a = batching.dataset2.get_idx_split()
a
b = a ['train']

dataset_keys = ['edge_index','edge_feat','node_feat','num_nodes']
#print(first_entry)
#print(type(first_entry))

test_tuple = ({'X': [1,2,3], 'Y': [2,3]}, {'X': [5,2,4], 'Y': [1,3]}, {'X': [1,1,3], 'Y': [2,1]})
for key, value in first_entry[0].items(): 
    print(key)

#print(first_entry[0]['edge_feat'])
#print(batching.dataset[1][0]['edge_feat'])


print(batching.dataset2[1][0]['edge_index'])


edge_index
edge_feat
node_feat
num_nodes
[[ 0  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10  9 11 11 12
   5 13 13 14 13  2 12  6]
 [ 1  0  2  1  3  2  4  3  5  4  6  5  7  6  8  7  9  8 10  9 11  9 12 11
  13  5 14 13  2 13  6 12]]


In [3]:
my_test_ds = batching.make_inputs(batching.dataset2)
type(my_test_ds)

for key, value in my_test_ds.items(): 
    print(key)

train_ds = my_test_ds['train']

train_ds

train
valid
test


<FlatMapDataset element_spec=({'X': TensorSpec(shape=(None, 9), dtype=tf.float32, name=None), 'ref_A': TensorSpec(shape=<unknown>, dtype=tf.int32, name=None), 'ref_B': TensorSpec(shape=<unknown>, dtype=tf.int32, name=None), 'num_nodes': TensorSpec(shape=<unknown>, dtype=tf.int32, name=None)}, TensorSpec(shape=(None, 128), dtype=tf.float32, name=None))>

In [4]:
my_batch = batching.make_inputs(batching.dataset2)
my_train_batch = my_batch['train']
type(my_train_batch)
test_dict = dict()

for entry in my_train_batch:
    for key, value in entry[0].items():
        test_dict[key] = value


type(test_dict)

for key, value in test_dict.items():
    print(key)

chunks_1= fy.chunks(test_dict, 1) #is generator 


X
ref_A
ref_B
num_nodes


In [5]:
batching.dataset2.labels

array([[ 0.,  0., nan, ..., nan, nan, nan],
       [ 0.,  0., nan, ..., nan, nan, nan],
       [nan,  0., nan, ..., nan, nan, nan],
       ...,
       [ 0.,  0.,  0., ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [6]:
my_batch1 = batching.make_inputs(batching.dataset1, batchsize=500)
training_batch1 = my_batch1['train']
# -----------------------------------------
my_batch2 = batching.make_inputs(batching.dataset2, batchsize=500)
training_batch2 = my_batch2['train']
fy.first(training_batch2)


({'X': <tf.Tensor: shape=(13513, 9), dtype=float32, numpy=
  array([[5., 0., 4., ..., 2., 0., 0.],
         [5., 0., 3., ..., 1., 0., 1.],
         [5., 0., 3., ..., 1., 0., 1.],
         ...,
         [6., 0., 2., ..., 1., 1., 1.],
         [6., 0., 2., ..., 1., 1., 1.],
         [5., 0., 3., ..., 1., 1., 1.]], dtype=float32)>,
  'ref_A': <tf.Tensor: shape=(29788,), dtype=int32, numpy=array([    0,     1,     1, ..., 13499, 13509, 13504])>,
  'ref_B': <tf.Tensor: shape=(29788,), dtype=int32, numpy=array([    1,     0,     2, ..., 13503, 13504, 13509])>,
  'num_nodes': <tf.Tensor: shape=(500,), dtype=int32, numpy=
  array([33, 36, 21, 19, 25, 22, 18, 23, 19, 35, 26, 22, 20, 13, 31, 20, 26,
         39, 28, 23, 17, 24, 17, 17, 17, 24, 24, 33, 28, 36, 33, 35, 42, 36,
         29, 39, 16, 26, 31, 28, 32, 29, 23, 27, 27, 21, 14, 23, 15, 20, 34,
         30, 23, 31, 35, 24, 21, 23, 15, 29, 36, 10, 28, 22, 29, 25, 26, 27,
         29, 28, 32, 25, 30, 24, 18, 36, 31, 26, 23, 25, 18, 20, 39, 2

In [32]:

test_labels = batching.dataset2.labels
exp_labels = list() 

def make_lables(list): 
    for i in range(30): 
        exp_labels.append(list[i])
    return tf.constant(exp_labels)
lables_work = make_lables(test_labels)

test_labels[test_labels== test_labels].shape

(34017170,)

In [8]:
import math

not_number = math.nan 
nn = math.nan 


print(not_number == nn)
#test

test_array = tf.constant([23,nn, 34, nn ,723, 1 ,1 ,2 ,345, nn, nn, nn, 34, nn])

False


In [26]:
def nan_function(list): 
    for i in test_array: 
        nn = math.nan
        if not isinstance(i/2, float): 
            if i/2 != nn:  
                i = 9999999


nan_function(test_array)
test_array

<tf.Tensor: shape=(14,), dtype=float32, numpy=
array([ 23.,  nan,  34.,  nan, 723.,   1.,   1.,   2., 345.,  nan,  nan,
        nan,  34.,  nan], dtype=float32)>

In [62]:
for i in test_array: 
    if not isinstance(i, float)and i != math.nan: 
        print(i)
       

tf.Tensor(23.0, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)
tf.Tensor(34.0, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)
tf.Tensor(723.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(345.0, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)
tf.Tensor(34.0, shape=(), dtype=float32)
tf.Tensor(nan, shape=(), dtype=float32)


In [43]:
test_method = batching.make_tf_datasets(batching.dataset2, 200, True)


In [44]:
test_method['test']
fy.first(test_method['test'])

({'X': <tf.Tensor: shape=(5491, 9), dtype=float32, numpy=
  array([[5., 0., 4., ..., 2., 0., 0.],
         [5., 0., 3., ..., 1., 0., 1.],
         [5., 0., 3., ..., 1., 0., 1.],
         ...,
         [5., 0., 3., ..., 1., 0., 1.],
         [7., 0., 1., ..., 1., 0., 0.],
         [7., 0., 2., ..., 1., 0., 1.]], dtype=float32)>,
  'ref_A': <tf.Tensor: shape=(12126,), dtype=int32, numpy=array([   0,    1,    1, ..., 5470, 5485, 5481])>,
  'ref_B': <tf.Tensor: shape=(12126,), dtype=int32, numpy=array([   1,    0,    2, ..., 5490, 5481, 5485])>,
  'num_nodes': <tf.Tensor: shape=(200,), dtype=int32, numpy=
  array([33, 36, 21, 19, 25, 22, 18, 23, 19, 35, 26, 22, 20, 13, 31, 20, 26,
         39, 28, 23, 17, 24, 17, 17, 17, 24, 24, 33, 28, 36, 33, 35, 42, 36,
         29, 39, 16, 26, 31, 28, 32, 29, 23, 27, 27, 21, 14, 23, 15, 20, 34,
         30, 23, 31, 35, 24, 21, 23, 15, 29, 36, 10, 28, 22, 29, 25, 26, 27,
         29, 28, 32, 25, 30, 24, 18, 36, 31, 26, 23, 25, 18, 20, 39, 26, 25,
      

In [47]:
inputs1 = m.create_input(batching.dataset1)
inputs2 = m.create_input(batching.dataset2, True)


In [48]:

model_1 = m.create_model(['ginConvo', 'ginConvo', 'ginConvo', 'Pooling', 'Dense'], inputs1, units=128, activation="relu")
model_2 = m.create_model(['Convolution','Convolution', 'Pooling', 'Dense'], inputs2)


In [50]:
model_2.summary() 


Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 X (InputLayer)                 [(None, 9)]          0           []                               
                                                                                                  
 label_mask (InputLayer)        [(None, 9)]          0           []                               
                                                                                                  
 num_nodes (InputLayer)         [(None,)]            0           []                               
                                                                                                  
 ref_A (InputLayer)             [(None,)]            0           []                               
                                                                                            