In [7]:
import tensorflow as tf 
import tensorflow.keras as keras 



In [3]:
tf.constant([1,2,3]) + 1 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [32]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [29]:
class MyLayer(keras.layers.Layer):
    def __init__(self): 
        super().__init__()
    def build(self, input_shape): 
        self.w = self.add_weight(shape= (1,), dtype = tf.float32)
    def call(self, X): 
        return tf.cast(X, tf.float32)*self.w


In [56]:
input = keras.layers.Input(shape=(1,), dtype = tf.int32)
out = MyLayer()(input)
m = keras.Model(inputs = input, outputs = out)
m.compile(optimizer=tf.keras.optimizers.Adam(lr= 0.1),
              loss='mean_squared_error', metrics=[tf.keras.metrics.RootMeanSquaredError()])



In [58]:
m.fit(tf.constant([1,]), tf.constant([1.,]), epochs = 100)

Epoch 1/100
1/1 [==============================] - 0s 18ms/step - loss: 8.2731e-09 - root_mean_squared_error: 9.0957e-05
Epoch 2/100
1/1 [==============================] - 0s 10ms/step - loss: 2.2737e-09 - root_mean_squared_error: 4.7684e-05
Epoch 3/100
1/1 [==============================] - 0s 10ms/step - loss: 6.9633e-11 - root_mean_squared_error: 8.3447e-06
Epoch 4/100
1/1 [==============================] - 0s 9ms/step - loss: 7.4849e-10 - root_mean_squared_error: 2.7359e-05
Epoch 5/100
1/1 [==============================] - 0s 8ms/step - loss: 3.5385e-09 - root_mean_squared_error: 5.9485e-05
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 7.8029e-09 - root_mean_squared_error: 8.8334e-05
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 1.3001e-08 - root_mean_squared_error: 1.1402e-04
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 1.8712e-08 - root_mean_squared_error: 1.3679e-04
Epoch 9/100
1/1 [==================

In [59]:
m(tf.constant(1))

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.0000046], dtype=float32)>

In [62]:
X = tf.constant([[1,1],[2,1],[1,2]],dtype=tf.float32)
ref_a = tf.constant([0, 0])
ref_b = tf.constant([1, 2])
#coordinates of A 
inputs=dict(X=X,ref_a=ref_a,ref_b=ref_b)
inputs
tf.gather, tf.scatter

{'X': <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[1., 1.],
        [2., 1.],
        [1., 2.]], dtype=float32)>,
 'ref_a': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0])>,
 'ref_b': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>}