In [48]:
%load_ext autoreload
%autoreload 2
import tensorflow as tf
import numpy as np
import batching 
import convL 
import convo 
import model 
import poolingL 
import funcy as fy 


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [49]:
first_graph =(batching.dataset[0])
print(type(first_graph))
print(first_graph)


<class 'tuple'>
({'edge_index': array([[ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,
         6,  9,  4, 10, 10, 11, 11, 12, 12, 13, 11, 14, 14, 15, 15, 16,
        16, 17, 15, 18,  9,  2, 18,  4],
       [ 1,  0,  2,  1,  3,  2,  4,  3,  5,  4,  6,  5,  7,  6,  8,  7,
         9,  6, 10,  4, 11, 10, 12, 11, 13, 12, 14, 11, 15, 14, 16, 15,
        17, 16, 18, 15,  2,  9,  4, 18]], dtype=int64), 'edge_feat': array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0

In [53]:
from collections import ChainMap
G = {
    'X': np.array([1,1,1]), 
    'ref_A': np.array([0,1]),
    'ref_B': np.array([1,2])}
H = {
    'X': np.array([1,1,2,2]), 
    'ref_A': np.array([0,1,1,0]),
    'ref_B': np.array([1,3,2,2])}

test_batch = dict(G, **H)

for key, value in test_batch.items(): 
    print(key, value)

X [1 1 2 2]
ref_A [0 1 1 0]
ref_B [1 3 2 2]


In [71]:
#test_chunks = fy.chunks()

n = fy.chunks(2, [1,2,34,56,7,8,23,4])
print(n)

<generator object _cut_seq.<locals>.<genexpr> at 0x000001373C2BA180>


In [74]:
# try batching on reg data structures 

type(batching.first_batch)
for key, value in batching.first_batch.items(): 
    print(key, value)


# X [[]] 

X [[5 0 4 ... 2 0 0]
 [5 0 4 ... 2 0 0]
 [5 0 3 ... 1 0 1]
 ...
 [6 0 2 ... 1 1 1]
 [5 0 3 ... 1 1 1]
 [5 0 3 ... 1 1 1]]
ref_A [  0   1   1 ... 593 600 596]
ref_B [  1   0   2 ... 601 596 600]
num_nodes [19 39 21 24 10 16 10 18 26 20 13 22 20 42 12 12 12 23 29 37 14  9 18 14
 41 15 23 16 18  9]
