In [19]:
import batching
import poolingL
import modularized as m
import gin
import convL
import convo as c
from tensorflow import keras
import numpy as np
import funcy as fy
from ogb.graphproppred import GraphPropPredDataset
import ogb
import tensorflow_addons as tfa
import tensorflow as tf
%autoreload 2
%reload_ext autoreload


UsageError: Line magic function `%autoreload` not found.


In [20]:

# load ogb dataset 
dataset1 = GraphPropPredDataset(name='ogbg-molhiv')
dataset2 = GraphPropPredDataset(name='ogbg-molpcba')

In [21]:
dataset1[0][0]['edge_index']

X = dataset1[0][0]['node_feat']
refA = tf.constant(dataset1[0][0]['edge_index'][0], dtype = tf.int32)
refB = tf.constant(dataset1[0][0]['edge_index'][1], dtype = tf.int32)
X_b = tf.cast((tf.gather(X, refB, axis=0)),dtype=tf.int32)
X_aggregate = tf.scatter_nd(tf.expand_dims(refA, axis=- 1), X_b, shape=tf.shape(X))


# DropOut (false, false)
# DropNode (true, false)
# DropEdge (true, true)
# GDC (false, true)

In [22]:
refA
shape = tf.shape(refA)[0]
refA

<tf.Tensor: shape=(40,), dtype=int32, numpy=
array([ 0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  6,
        9,  4, 10, 10, 11, 11, 12, 12, 13, 11, 14, 14, 15, 15, 16, 16, 17,
       15, 18,  9,  2, 18,  4])>

In [35]:
# get_shape --> DROP NODE 
drop_node_shape = c.get_shape(X, True)
dropNode_result = X * c.dropout_mask(0.7 , drop_node_shape)


X == dropNode_result
#c.dropout_mask(0.7, drop_node_shape)

#dropNode_result

<tf.Tensor: shape=(19, 9), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False,  True, False, False,  True,  True, False,  True, False],
       [False,  True, False, False,  True,  True, False,  True, False],
       [False,  True, False, False,  True,  True, False,  True, False],
       [False,  True, False, False,  True,  True, False,  True, False],
       [False,  True, False, False, False,  True, False,  True,  True],
       [False,  True, False, False, False,  True, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  Tr

In [27]:
# get_shape --> DROP OUT 
dropout_shape = c.get_shape(X, False) 
drop_out_result = X * c.dropout_mask(0.70, dropout_shape)

drop_out_result

<tf.Tensor: shape=(19, 9), dtype=float32, numpy=
array([[0., 0., 4., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 1.],
       [7., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 4., 2., 0., 0., 5., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [5., 0., 0., 5., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 4., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 6., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 4., 5., 0., 0., 2., 0., 0.],
       [0., 0., 0., 5., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 2., 0., 2., 0., 0.],
       [5., 0., 0., 5., 0., 0., 0., 0., 0.],
       [7., 0., 0., 0., 0., 0., 1., 0., 1.]], dtype=float32)>

In [11]:
def quicksort_inplace(arr, low=0, high=None):
    if high is None:
        high = len(arr) - 1
    if low < high:
        p = partition(arr, low, high)
        quicksort_inplace(arr, low, p - 1)
        quicksort_inplace(arr, p + 1, high)


def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] < pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i+1], arr[high] = arr[high], arr[i+1]
    return i + 1


In [12]:
array = [12, 2, 1, 5, 57, 9, 2, 2, 41, 12, 34]
quicksort_inplace(array, low = 0)

array


[1, 2, 2, 2, 5, 9, 12, 12, 34, 41, 57]